// Package v1alpha1 contains DeployLens CRD type definitions.
package v1alpha1

import (
	"time"
)

// PostgresWatch declares which Postgres cluster to monitor and sensitivity settings.
type PostgresWatch struct {
	// Name is the unique identifier of this watch configuration.
	Name string `json:"name"`
	// Namespace is the Kubernetes namespace of the target CNPG Cluster.
	Namespace string `json:"namespace"`
	// ClusterName is the name of the CloudNativePG Cluster resource.
	ClusterName string `json:"clusterName"`
	// DSN is the Postgres connection string (host, port, user, password, dbname).
	DSN string `json:"dsn"`
	// ScrapeIntervalSeconds controls how often pg_stat_statements is read (default: 60).
	ScrapeIntervalSeconds int `json:"scrapeIntervalSeconds,omitempty"`
	// WindowMinutes defines how many minutes before/after a deploy to analyse (default: 30).
	WindowMinutes int `json:"windowMinutes,omitempty"`
	// MinExecutions is the minimum number of executions a query needs in each window
	// to be considered for regression detection (default: 10).
	MinExecutions int64 `json:"minExecutions,omitempty"`
	// LatencyChangeThreshold is the minimum relative increase in mean latency (e.g. 0.20
	// means 20 %) required for a finding to be reported (default: 0.20).
	LatencyChangeThreshold float64 `json:"latencyChangeThreshold,omitempty"`
	// CriticalQueryIDs lists pg_stat_statements queryids that should always be evaluated
	// regardless of MinExecutions.
	CriticalQueryIDs []int64 `json:"criticalQueryIDs,omitempty"`
}

// DeploySource describes where deploy events come from and how they map to a
// PostgresWatch.
type DeploySource struct {
	// Name is the unique identifier of this deploy source.
	Name string `json:"name"`
	// Namespace is the Kubernetes namespace.
	Namespace string `json:"namespace"`
	// PostgresWatchRef references the PostgresWatch that this source feeds.
	PostgresWatchRef string `json:"postgresWatchRef"`
	// SourceType describes the origin system: argocd, argo-rollouts, flux.
	SourceType string `json:"sourceType"`
	// AppName is the ArgoCD Application / Rollout / Flux Kustomization name to filter
	// on (empty = accept all).
	AppName string `json:"appName,omitempty"`
}

// DeployEvent is a normalised deploy event ingested from any supported source.
type DeployEvent struct {
	// ID is a unique identifier generated by the ingester.
	ID string `json:"id"`
	// Source references the DeploySource that produced this event.
	Source string `json:"source"`
	// App is the application name (ArgoCD Application, Rollout, or Flux Kustomization).
	App string `json:"app"`
	// Cluster is the target cluster identifier.
	Cluster string `json:"cluster"`
	// Namespace is the target namespace.
	Namespace string `json:"namespace"`
	// Revision is the Git commit SHA or image tag that was deployed.
	Revision string `json:"revision"`
	// ImageTag is the container image tag, if available.
	ImageTag string `json:"imageTag,omitempty"`
	// Timestamp is when the deploy completed.
	Timestamp time.Time `json:"timestamp"`
}

// PerformanceRegressionStatus reflects the outcome of the correlation analysis.
type PerformanceRegressionStatus string

const (
	// StatusDetected means a statistically significant regression was found.
	StatusDetected PerformanceRegressionStatus = "Detected"
	// StatusNoRegression means no regression was found in the analysis window.
	StatusNoRegression PerformanceRegressionStatus = "NoRegression"
	// StatusInsufficientData means there were not enough samples to reach a conclusion.
	StatusInsufficientData PerformanceRegressionStatus = "InsufficientData"
)

// PerformanceRegression is created by the Correlation Engine when it analyses a deploy.
type PerformanceRegression struct {
	// Name is a unique identifier (usually derived from deploy event ID + queryid).
	Name string `json:"name"`
	// Namespace is the Kubernetes namespace.
	Namespace string `json:"namespace"`
	// DeployEventID references the DeployEvent that triggered this analysis.
	DeployEventID string `json:"deployEventId"`
	// QueryID is the pg_stat_statements queryid.
	QueryID int64 `json:"queryId"`
	// QueryText is a normalised excerpt of the query for human display.
	QueryText string `json:"queryText"`
	// Status is the analysis outcome.
	Status PerformanceRegressionStatus `json:"status"`
	// ConfidenceScore is a value between 0 and 1 expressing the algorithm's confidence.
	ConfidenceScore float64 `json:"confidenceScore"`
	// MeanLatencyBefore is mean execution time (µs) in the pre-deploy window.
	MeanLatencyBefore float64 `json:"meanLatencyBefore"`
	// MeanLatencyAfter is mean execution time (µs) in the post-deploy window.
	MeanLatencyAfter float64 `json:"meanLatencyAfter"`
	// LatencyChangeFactor is MeanLatencyAfter / MeanLatencyBefore.
	LatencyChangeFactor float64 `json:"latencyChangeFactor"`
	// ExternalCauseSuspected is true when CPU/IO metrics also changed, suggesting the
	// regression may not be caused solely by the deploy.
	ExternalCauseSuspected bool `json:"externalCauseSuspected,omitempty"`
	// CreatedAt is when this object was created.
	CreatedAt time.Time `json:"createdAt"`
}
